Message:
  Wrong-Commands: 'Usage: /azbar reload'
  Reload-Successful: 'Reload Successfully'
  NoPermission: 'You not have permission to use command'

index: 16
#Please Dont change this!!
AzHotBar:
  Health:
    Max: "%azhotbar_maxhp%"
    Current: "%azhotbar_currenthp%"
  Food:
    Max: "%azhotbar_maxfood%"
    Current: "%azhotbar_currentfood%"
  Armor:
    Max: "%azhotbar_maxarmor%"
    Current: "%azhotbar_currentarmor%"
  Oxy:
    Max: "%azhotbar_maxoxy%"
    Current: "%azhotbar_currentoxy%"
  Mana:
    Max: "%azhotbar_maxmana%"
    Current: "%azhotbar_currentmana%"
  Stamina:
    Max: "%azhotbar_maxstamina%"
    Current: "%azhotbar_currentstamina%"

#MMOCore: %azhotbar_mana% & %azhotbar_stamina%
BossBar:
  Prefix: "@"
  Title: "HP: %azhotbar_hp%"
