name: AzBarFix
version: '${project.version}'
main: com.azpixel.AzBarFix
api-version: '1.13'
depend:
  - Geyser-Spigot
  - PlaceholderAPI
authors:
  - ItzMintDzX
  - LZ5509
commands:
  azbar:
    description: "AzPixel HotBar"
    aliases:
      - azb
permissions:
  azhotbar.admin:
    description: "Permissions for azhotbar"
    default: op
