name: AzBarFix
version: '${project.version}'
main: com.azpixel.AzBarFix
api-version: '1.20'
depend:
  - Geyser-Spigot
  - PlaceholderAPI
  - MMOCore
author: ItzMintDzX (AzPixel-Team)
commands:
  azbar:
    description: "AzPixel HotBar"
    aliases:
      - azb
permissions:
  azhotbar.admin:
    description: "Permissions for azhotbar"
    default: op
