jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - name: Set up JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: ${{ inputs.java }}
        distribution: ${{ inputs.distribution }}
        cache: maven
    - name: Build with Maven
      run: |
        ${{ inputs.commands }}
        mvn ${{ inputs.tasks }}
      env:
        MAVEN_OPTS: ${{ inputs.opts }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.target }}
