name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '17'
        distribution: "temurin"
        cache: maven
    - name: Build with Maven
      run: mvn clean package
      env:
        MAVEN_OPTS: "-Xmx2048m --illegal-access=permit"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AZBarFix
        path: target/*.jar
